apiVersion: v1
kind: Service
metadata:
  name: apache-helm
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apache-helm.selectorLabels" . | nindent 4 }}
