apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
spec:
  replicas: {{ .Values.replicaCount }} # Fetching replica count from values.yaml
  selector:
    matchLabels:
      app.kubernetes.io/name: 
      app.kubernetes.io/instance: 
  template:
    metadata:
      labels:
    spec:
      containers:
        - 
        